# Generated by Django 5.2.4 on 2025-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="Date_created",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="Status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="total_price",
            new_name="total_amount",
        ),
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
