# Generated by Django 5.2.4 on 2025-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("restaurant", "Restaurant"), ("customer", "Customer")],
                max_length=20,
            ),
        ),
    ]
