# Generated by Django 5.2.4 on 2025-08-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurantprofile",
            old_name="adress",
            new_name="address",
        ),
    ]
