# Generated by Django 5.2.4 on 2025-08-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_rename_adress_restaurantprofile_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantprofile",
            name="opening_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
