# Generated by Django 5.2.4 on 2025-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_alter_restaurantprofile_opening_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dish",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="dish",
            name="qty",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="restaurantprofile",
            name="contact_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="restaurantprofile",
            name="opening_hours",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
